name: Dispatch a SSH session

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        runon: [windows-2022]
        #runon: [windows-2022, windows-2019, Ubuntu-22.04, Ubuntu-20.04, macOS-14, macOS-13, macOS-12, macOS-11]
        # , windows-2022 , ubuntu-18.04 , ubuntu-20.04 , macos-10.15 , macos-11.0]
      fail-fast: false

    runs-on: windows-2022
    steps:
    - name: Install environment
      run: |
        git clone -b veracrypt-dcs --recursive https://github.com/8NEZNhg7U73i/edk2
        choco install everything
        choco install es
        choco install nasm
        choco install iasl
        choco install cygwin
        choco install visualstudio2019community --package-parameters " --installPath D:\VS2019 --allWorkloads --includeRecommended --includeOptional --passive --locale en-US"
        #choco install visualstudio2019buildtools
        setx NASM_PREFIX C:\Program Files\NASM\
        setx CYGWIN_HOME C:\tools\cygwin\
    - name: Start SSH session
      uses: 8NEZNhg7U73i/debug-via-ssh@main
      with:
        SSH_PASS: ${{ secrets.SSH_PASS }}
        ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
        ZEROTIER_CONFIG: ${{ secrets.ZEROTIER_CONFIG }}
        ZEROTIER_SECRET: ${{ secrets.ZEROTIER_SECRET }}
        ZEROTIER_PUBLIC: ${{ secrets.ZEROTIER_PUBLIC }}
        ZEROTIER_AUTHTOKEN: ${{ secrets.ZEROTIER_AUTHTOKEN }}
        #ZEROTIER_TIMEOUT: ${{ secrets.ZEROTIER_TIMEOUT }}

  test1:
    runs-on: windows-2019
    steps:
    - name: Install environment
      run: |
        git clone -b veracrypt-dcs --recursive https://github.com/8NEZNhg7U73i/edk2
        choco install everything
        choco install es
        choco install nasm
        choco install iasl
        choco install cygwin
        #choco install visualstudio2019Enterprise --package-parameters "--no-update --allWorkloads --includeRecommended --includeOptional --passive --locale en-US"
        #choco install visualstudio2019buildtools
        setx NASM_PREFIX C:\Program Files\NASM\
        setx CYGWIN_HOME C:\tools\cygwin\
    - name: Start SSH session
      uses: 8NEZNhg7U73i/debug-via-ssh@main
      with:
        SSH_PASS: ${{ secrets.SSH_PASS }}
        ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
        ZEROTIER_CONFIG: ${{ secrets.ZEROTIER_CONFIG }}
        ZEROTIER_SECRET: ${{ secrets.ZEROTIER_SECRET }}
        ZEROTIER_PUBLIC: ${{ secrets.ZEROTIER_PUBLIC }}
        ZEROTIER_AUTHTOKEN: ${{ secrets.ZEROTIER_AUTHTOKEN }}
        #ZEROTIER_TIMEOUT: ${{ secrets.ZEROTIER_TIMEOUT }}

